### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by KirboGames** [KirboGames/S.A.U.W.-#40]
**Describe the bug**

Crash when you click `Exit` in `pause_interface`

**To Reproduce**

1. Open `pause_interface`
2. Click on `Exit`
3. Crash

**Platform**

- [x] Android
- [x] Desktop

**Log**

```
java.lang.RuntimeException: It works, but you shouldn't use it :moyai:
	at com.kgc.sauw.game.SAUW.dispose(SAUW.java:79)
	at com.kgc.sauw.game.Game.closeGame(Game.java:84)
	at com.kgc.sauw.core.gui.InterfaceElement.onClick(InterfaceElement.java:81)
	at com.kgc.sauw.core.gui.InterfaceElement.update(InterfaceElement.java:64)
	at com.kgc.sauw.core.gui.elements.Layout.tick(Layout.java:71)
	at com.kgc.sauw.core.gui.InterfaceElement.update(InterfaceElement.java:75)
	at com.kgc.sauw.core.gui.Interface.update(Interface.java:136)
	at com.kgc.sauw.core.gui.Interfaces.updateInterfaces(Interfaces.java:40)
	at com.kgc.sauw.game.Game.render(Game.java:163)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
```

**Comment by KirboGames** [comment]
Ok...

![image](https://user-images.githubusercontent.com/62571450/153644322-7dc4d91d-e1bc-49e3-adc3-1155015f515f.png)
